# Generated by Django 5.0.1 on 2024-01-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='./media/product/')),
            ],
        ),
    ]
