# Generated by Django 5.0.1 on 2024-01-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_alter_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
