# Generated by Django 5.0.1 on 2024-02-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='usertype',
            field=models.BooleanField(default=0),
        ),
    ]
